version: 2

jobs:
  build-job:
    docker:
      - image: circleci/php:7.1.5-browsers
    working_directory: ~/wu2018
    steps:
      - checkout
      - run: curl -sS https://getcomposer.org/installer | php -- --filename=composer
      - run: ./composer install
      - run: ./vendor/bin/phpunit
  deploy-job:
    machine:
      enabled: true
    working_directory: ~/wu2018
    steps:
      - run: ssh ubuntu@ec2-13-229-52-5.ap-southeast-1.compute.amazonaws.com "sh deploy.sh"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job

           